# Site settings
title: the nerdie foodie
description: A blog about food by a nerd
keywords: Food, Nerdy
author: Catalina C-S
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
